http:
  middlewares:
    https-redirect:
      redirectScheme:
        scheme: https

tls:
  certificates:
    - certFile: "/certs/fullchain.pem"
      keyfile: "/certs/privkey.pem"
      stores:
        - default
  stores:
    default:
      defaultCertificate:
        certFile: "/certs/fullchain.pem"
        keyFile: "/certs/privkey.pem"