version: '3.7'

services:
  phpmyadmin:
    container_name: phpmyadmin
    image: sk278/phpmyadmin-armhf:4.8.3
    restart: always
    networks:
      - web
    environment:
      - PMA_HOST=172.17.0.1
      - MYSQL_USERNAME=${MYSQL_USERNAME}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"

      - "traefik.http.routers.phpmyadmin.entrypoints=websecure"
      - "traefik.http.routers.phpmyadmin.rule=Host(`phpmyadmin.${DOMAINNAME}`)"
      - "traefik.http.routers.phpmyadmin.tls=true"
      - "traefik.http.routers.phpmyadmin.service=phpmyadmin@docker"
      - "traefik.http.services.phpmyadmin.loadbalancer.server.port=80"

networks:
  web:
    external: true

